# !!! WRONG GRAPH --> ROLLED BACK BY 20241120102827-rollback.sparql

# USER
# - firstName: Autonoom gemeentebedrijf
# - familyName: AGB Ronse
# GROUP
# - name: AGB Ronse

PREFIX ext:<http://mu.semte.ch/vocabularies/ext/>

INSERT DATA {
  GRAPH <http://data.lblod.info/id/account/10e7db854c9e2249bf37289887b5fed0> {
    <http://data.lblod.info/id/account/10e7db854c9e2249bf37289887b5fed0> ext:sessionRole "LoketLB-admin" .
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/account/10e7db854c9e2249bf37289887b5fed0> ext:sessionRole "LoketLB-admin" .
  }
}