PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

# USER
# - firstName: Autonome verzorginstelling
# - familyName: abc
# GROUP
# - name: abc

INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/account/5b863804e864c3cdc2989b2729e68680> ext:sessionRole "LoketLB-admin" .
  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/account/5b863804e864c3cdc2989b2729e68680> ?p ?o .
  }
};

# USER
# - firstName: Autonoom gemeentebedrijf
# - familyName: AGB Ronse
# GROUP
# - name: AGB Ronse

INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/account/10e7db854c9e2249bf37289887b5fed0> ext:sessionRole "LoketLB-admin" .
  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/account/10e7db854c9e2249bf37289887b5fed0> ?p ?o .
  }
};

# USER
# - firstName: Autonome verzorginstelling
# - familyName: AZ Lokeren AV
# GROUP
# - name: AZ Lokeren AV

INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/account/23596595695463e99a7f8aa72495470c> ext:sessionRole "LoketLB-admin" .
  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/account/23596595695463e99a7f8aa72495470c> ?p ?o .
  }
}