PREFIX bboExtension: <https://www.teamingai-project.eg/BBOExtension#>
PREFIX bbo: <https://www.irit.fr/recherches/MELODI/ontologies/BBO#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX ns1: <http://lblod.data.gift/concepts/>

INSERT {
    GRAPH <http://mu.semte.ch/graphs/antwerpen> {
        ?s org:classification ?classification .
    }
} WHERE {
    GRAPH <http://mu.semte.ch/graphs/antwerpen> {
        ?s a ?type .
        FILTER NOT EXISTS { ?s org:classification ?existingClassification } .
        VALUES (?type ?classification) {
            (bbo:IntermediateThrowEvent ns1:6f1559a6-e0af-41bf-b14e-ff2597a3d8dc)
            (bbo:MessageEventDefinition ns1:d45c81c4-ab87-4dc1-b324-1c3289e2c36a)
            (bboExtension:LaneSet ns1:73c4071b-a618-49df-8119-573a1e21e652)
            (bbo:ErrorEventDefinition ns1:107c7feb-64ff-409f-a5ce-1e85324274fc)
            (bboExtension:DataInputAssociation ns1:7a53a259-0e26-4688-8137-be50458264ec)
            (bbo:ExclusiveGateway ns1:0bf0aea4-798d-4d7a-bd44-34f09f763eb3)
            (bboExtension:DataStoreReference ns1:b5de5008-7aeb-41c5-a2f2-26f1d4ca6d49)
            (bboExtension:DataOutputAssociation ns1:63da1337-6cd7-441c-a5c1-940f2fbd0f34)
            (bboExtension:Lane ns1:003fb962-c26b-468d-9baa-7a03d84c9322)
            (bbo:BoundaryEvent ns1:9a72a481-d111-405b-903b-18242e121502)
            (bboExtension:Collaboration ns1:ff8338d3-c491-413c-aae3-2a57dc3f75f5)
            (bbo:StartEvent ns1:298c0ed5-2624-4865-9c87-439d89640746)
            (bboExtension:Participant ns1:9a54f457-bfc3-46ba-93db-560eaaa183d3)
            (bbo:EndEvent ns1:55e98451-1f29-420c-87e3-3e01a7d5abc5)
            (bboExtension:TextAnnotation ns1:05dfacae-2772-458f-a54e-b996b0499501)
            (bbo:SequenceFlow ns1:e146c432-9a2f-41aa-b9a1-5efb8a8174e4)
            (bboExtension:DataObject ns1:3e0a146b-b483-40e7-a901-3144d5be2ee2)
            (bboExtension:MessageFlow ns1:28b6c81b-e493-4dc4-b700-d062cc08e86a)
            (bbo:Task ns1:3c8764ac-576d-4b4f-ae58-c42d30265240)
            (bbo:Property ns1:e7bc4c02-f476-430a-b3a0-2fa62e9245eb)
            (bboExtension:Association ns1:00cbc3c9-b2a8-4474-bbe9-c3a977f3feaf)
            (bbo:SubProcess ns1:270b79df-7a22-4064-a8a0-f5713873700d)
            (bboExtension:DataObjectReference ns1:ad8ee890-12a8-4a8a-bb23-10b3b2403df0)
            (bbo:ParallelGateway ns1:5099bb41-9d87-475c-80d0-5767ba32b0bb)
            (bbo:ExclusiveGateway ns1:0bf0aea4-798d-4d7a-bd44-34f09f763eb3)
            (bbo:Error ns1:cc636682-385a-4e63-8043-740d34e06254)
            (bbo:ScriptTask ns1:2691ce7b-82ae-4a66-ba8a-d84d5103a69a)
            (bbo:ServiceTask ns1:ca45e504-9421-4916-9f73-6500b9f45095)
            (bbo:ReceiveTask ns1:3c8764ac-576d-4b4f-ae58-c42d30265240)
            (bbo:UserTask ns1:8b23ea64-8748-46e6-90ce-dd85cfdafe8d)
            (bbo:ManualTask ns1:969d520f-2946-4323-940a-b4e21891d428)
            (bbo:SendTask ns1:6c3de872-2ddf-465a-941b-3b7080d09866)
            (bbo:BusinessRuleTask ns1:546044f1-455c-4949-8d45-df024bc76b49)
            (bbo:Process ns1:0996925f-9d2c-497c-86df-fad62d974790)
        }
    }
}
