(in-package :mu-cl-resources)

(define-resource file ()
  :class (s-prefix "nfo:FileDataObject")
  :properties `((:name :string ,(s-prefix "nfo:fileName"))
                (:format :string ,(s-prefix "dct:format"))
                (:size :number ,(s-prefix "nfo:fileSize"))
                (:extension :string ,(s-prefix "dbpedia:fileExtension"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:status :url ,(s-prefix "adms:status")))
  :has-one `((file :via ,(s-prefix "nie:dataSource")
                   :inverse t
                   :as "download")
             (file :via ,(s-prefix "prov:wasDerivedFrom")
                   :as "vsdx-file"))
  :has-many `((process :via ,(s-prefix "nie:isPartOf")
                       :as "processes")
              (file :via ,(s-prefix "prov:wasDerivedFrom")
                    :inverse t
                    :as "bpmn-files"))
  :resource-base (s-url "http://data.lblod.info/files/")
  :features `(include-uri)
  :on-path "files")