(in-package :mu-cl-resources)

(add-prefix "ext" "http://mu.semte.ch/vocabularies/ext/")
(add-prefix "bbo" "https://www.irit.fr/recherches/MELODI/ontologies/BBO#")
(add-prefix "bboExtension" "https://www.teamingai-project.eg/BBOExtension#")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "ql" "http://semweb.mmlab.be/ns/ql#")
(add-prefix "rami" "https://w3id.org/i40/rami#")
(add-prefix "rdfs" "http://www.w3.org/2000/01/rdf-schema#")
(add-prefix "rml" "http://semweb.mmlab.be/ns/rml#")
(add-prefix "rr" "http://www.w3.org/ns/r2rml#")
(add-prefix "teamingAI" "https://www.teamingai-project.eu/")
(add-prefix "obo" "http://purl.obolibrary.org/obo/")
(add-prefix "nfo" "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#")
(add-prefix "nie" "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "dbpedia" "http://dbpedia.org/ontology/")
(add-prefix "prov" "http://www.w3.org/ns/prov#")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "adms" "http://www.w3.org/ns/adms#")
(add-prefix "proces" "https://data.vlaanderen.be/ns/proces#")
(add-prefix "cogs" "http://vocab.deri.ie/cogs#")
(add-prefix "task" "http://redpencil.data.gift/vocabularies/tasks/")