PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX adms: <http://www.w3.org/ns/adms#>

DELETE {
    GRAPH <http://mu.semte.ch/graphs/antwerpen> {
        ?s ext:isArchived true .
    }
}
INSERT {
    GRAPH <http://mu.semte.ch/graphs/antwerpen> {
        ?s adms:status <http://lblod.data.gift/concepts/concept-status/gearchiveerd> .
    }
}
WHERE {
    GRAPH <http://mu.semte.ch/graphs/antwerpen> {
        ?s ext:isArchived true .
    }
}
